app_blog/urls.py
from django.urls import path
from app_blog import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<pk>/', views.UpdateBlog.as_view(), name='update'),
    path('manage/', views.MyBlog.as_view(), name='manage'),
    path('delete/<pk>/', views.DeleteBlogView.as_view(), name='delete'),
    path('blog/<slug:slug>/', views.single_blog, name='blog'),
    path('like/<pk>/', views.like_blog, name='like'),
    path('dislike/<pk>/', views.dislike_blog, name='dislike'),
]

app_login/urls.py
from django.urls import path
from app_login.views import signup, login, logout, profile, profile_update, profile_extra, profile_extra_update, password_change

app_name = 'app_login'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('update/', profile_update, name='update'),
    path('extra/', profile_extra, name='extra'),
    path('modify/', profile_extra_update, name='modify'),
    path('password/', password_change, name='password'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app_login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars', verbose_name="аватар", null=True, blank=True)
    bio = models.TextField(verbose_name='о себе', null=True, blank=True)
    location = models.CharField(max_length=20, verbose_name="местоположение", null=True, blank=True)

    def __str__(self):
        return self.user.username

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from app_login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'bio', 'location')

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from app_login.forms import SignUpForm, ProfileUpdateForm, UserProfileForm
from django.contrib.auth import login as user_login, authenticate, logout as user_logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.urls import reverse


def signup(request):
    form = SignUpForm()
    registerd = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registerd = True
    context = {'form': form, 'registerd': registerd}
    return render(request, 'app_login/signup.html', context)


def login(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                user_login(request, user)
                return HttpResponseRedirect(reverse('app_blog:blogs'))
    context = {'form': form}
    return render(request, 'app_login/login.html', context)


@login_required
def logout(request):
    user_logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    context = {}
    return render(request, 'app_login/profile.html', context)


@login_required
def profile_update(request):
    current_user = request.user
    form = ProfileUpdateForm(instance=current_user)
    if request.method == 'POST':
        form = ProfileUpdateForm(data=request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
            # form = ProfileUpdateForm(instance=current_user)
    context = {'form': form, }
    return render(request, 'app_login/profile_update.html', context)


@login_required
def profile_extra(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    context = {'form': form, 'action': 'Add'}
    return render(request, 'app_login/profile_extra.html', context)


@login_required
def profile_extra_update(request):
    form = UserProfileForm(instance=request.user.user_profile)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    context = {'form': form, 'action': 'Update'}
    return render(request, 'app_login/profile_extra.html', context)


@login_required
def password_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    context = {'form': form, 'changed': changed}
    return render(request, 'app_login/password_change.html', context)

templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Войти в аккаунт - Эко-сообщество{% endblock  %}

{% block body_block %}

<div class="container m-auto w-50">
    <div class="card p-5">
        <h2 class="mb-4">Войти</h2>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3" value="Войти">
        </form>
        <br>
        <p>Еще нет аккаунта? <a href="{% url 'app_login:signup' %}">Зарегистрироваться</a></p>
    </div>
</div>

{% endblock  %}

templates/app_login/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Изменить пароль - Эко-сообщество{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
{% if changed %}
    <div class="alert alert-success" role="alert">
        Пароль успешно изменен! Перейдите на страницу <a href="{% url 'app_login:login' %}">входа</a>
    </div>
{% else %}
    <div class="card p-5 mb-5">
        <h2 class="mb-4">Изменение пароля</h2>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3 me-4" value="Изменить">
            <a class="btn btn-outline-danger mt-3" href="{% url 'app_login:profile' %}">Отменить</a>
        </form>
    </div>
{% endif %}
</div>
{% endblock  %}

templates/app_login/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}Профиль - Эко-сообщество{% endblock %}
{% block body_block %}
<div class="container m-auto">
    <div class="row">
        <div class="col-md-4 bg-dark text-light rounded-start">
            <div class="rounded mt-3 position-relative overflow-hidden" style="max-height:356px;">
                <img class="img-fluid w-100"
                {% if user.user_profile %}
                    src="/media/{{user.user_profile.avatar}}" 
                {% else %}
                    src="{% static 'images/default.png' %}"
                {% endif %}
                alt="">
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title d-inline">
                    {% if user.first_name and user.last_name %}
                        {{user.first_name}} {{user.last_name}}
                    {% endif %}
                    </h4>
                    <p class="card-text d-inline text-light">
                    <i class="bi bi-person-circle"></i> /{{user.username}}</p>
                </div>
                <p class="card-text text-light lead mb-0">
                <i class="bi bi-envelope-fill"></i>
                {{user.email}}</p>
                <p class="card-text text-light lead">
                <i class="bi bi-calendar3"></i>
                {{user.date_joined|date}}</p>
                <div class="input-group input-group-sm">
                    <span class="input-group-text bg-light" ><b>Изменить:</b></span>
                    <a {% if user.user_profile %}
                        href="{% url 'app_login:modify' %}"
                    {% else %}
                        href="{% url 'app_login:extra' %}"
                    {% endif %} class="btn btn-success">
                        <i class="bi bi-pencil-square me-1"></i>Профиль</a>
                    <a class="btn btn-primary" href="{% url 'app_login:update' %}">
                        <i class="bi bi-file-person me-1"></i>Личное</a>
                    <a class="btn btn-danger" href="{% url 'app_login:password' %}">
                        <i class="bi bi-shield-check me-1"></i>Пароль</a>
                </div>
            </div>
        </div>
        <div class="col-md-8 bg-light p-5 border border-2 border-dark rounded-end">
            <h5 class="display-5">Профиль</h5>
            <div class="card p-3 lead">{{user.user_profile.bio|default:"Добавьте информацию о себе"}}</div>
            <div class=" container mt-2 d-flex justify-content-between flex-wrap">
                <p class="lead d-inline"><kbd>
                    <i class="bi bi-geo-alt-fill"></i></kbd> 
                    {{user.user_profile.location|default:"Добавьте местоположение"}}</p>
            </div>
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5>Мои посты</h5>
                    <a href="{% url 'app_blog:manage' %}" class="btn btn-warning btn-sm">Управлять постами</a>
                </div>
                <div class="card-body">
                    <ul>
                    {% for blog in user.blog_author.all %}
                        <li><a class="text-decoration-none" href="{% url 'app_blog:blog' slug=blog.slug %}">{{blog.title}}</a></li>
                        {% empty %}
                        <li>У вас пока нет написанных постов</li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

templates/app_login/profile_extra.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Добавить информацию о себе - Эко-сообщество{% endblock %}
{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5">
        <h2>Заполнить информацию о себе</h2>
        <p class='lead'>Вы можете добавить фотографию, описание и свой адрес</p>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3 me-4" value="Добавить">
            <a class="btn btn-outline-danger mt-3" href="{% url 'app_login:profile' %}">Отменить</a>
        </form>
    </div>
</div>
{% endblock  %}

templates/app_login/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Изменение профиля - Эко-сообщество{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        <h2>Изменить аккаунт</h2>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3 me-4" value="Обновить">
            <a class="btn btn-outline-danger mt-3" href="{% url 'app_login:profile' %}">Отменить</a>
        </form>
    </div>
</div>
{% endblock  %}

templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Регистрация - Эко-сообщество{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
{% if registerd %}
    <div class="alert alert-success" role="alert">
        Аккаунт успешно зарегистрирован! <a href="{% url 'app_login:login' %}">Войти</a>
    </div>
{% else %}
    <div class="card p-5 mb-5">
        <h2>Регистрация</h2>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3" value="Создать аккаунт">
        </form>
        <br>
        <p>Уже есть аккаунт? <a class="" href="{% url 'app_login:login' %}">Войти</a></p>
    </div>
{% endif %}
</div>
{% endblock  %}