app_blog/urls.py
from django.urls import path
from app_blog import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<pk>/', views.UpdateBlog.as_view(), name='update'),
    path('manage/', views.MyBlog.as_view(), name='manage'),
    path('delete/<pk>/', views.DeleteBlogView.as_view(), name='delete'),
    path('blog/<slug:slug>/', views.single_blog, name='blog'),
    path('like/<pk>/', views.like_blog, name='like'),
    path('dislike/<pk>/', views.dislike_blog, name='dislike'),
]

app_login/urls.py
from django.urls import path
from app_login.views import signup, login, logout, profile, profile_update, profile_extra, profile_extra_update, password_change

app_name = 'app_login'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('update/', profile_update, name='update'),
    path('extra/', profile_extra, name='extra'),
    path('modify/', profile_extra_update, name='modify'),
    path('password/', password_change, name='password'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User


class EcologicalTopic(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "экологическая тема"
        verbose_name_plural = "экологические темы"


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_author')
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.SlugField(max_length=264, unique=True)
    text = models.TextField(verbose_name='текст')
    image = models.ImageField(upload_to='blogs', verbose_name='фотография')
    published = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    topics = models.ManyToManyField(EcologicalTopic, related_name="blogs", verbose_name="экологические темы")

    class Meta:
        ordering = ['-published', ]

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField(verbose_name='комментарий', default='')
    commented = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-commented',)

    def __str__(self):
        return self.comment


class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')

    def __str__(self):
        return f"{self.user} likes {self.blog}"

app_blog/forms.py
from django import forms
from app_blog.models import Comment, Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image', 'topics')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'text': forms.Textarea(attrs={'class': 'form-control mb-3'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control mb-3'}),
            'topics': forms.CheckboxSelectMultiple(),
        }


class CommentForm(forms.ModelForm):
    comment = forms.CharField(label="", widget=forms.Textarea(attrs={'rows': '1', }))

    class Meta:
        model = Comment
        fields = ('comment',)

app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.views.generic.base import TemplateView
from app_blog.models import Blog, Like
from uuid import uuid4
from app_blog.forms import CommentForm, BlogForm
from slugify import slugify


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    form_class = BlogForm

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.user = self.request.user
        blog_obj.image = self.request.FILES['image']
        blog_obj.slug = slugify(blog_obj.title) + '-' + str(uuid4())
        blog_obj.save()
        form.save_m2m()
        return HttpResponseRedirect(reverse('app_blog:blogs'))


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = 'app_blog/edit_blog.html'
    form_class = BlogForm

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.user = self.request.user
        blog_obj.image = self.request.FILES.get('image', blog_obj.image)
        blog_obj.slug = slugify(blog_obj.title) + '-' + str(uuid4())
        blog_obj.save()
        form.save_m2m()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('app_blog:blog', kwargs={'slug': self.object.slug})


class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'app_blog/my_blogs.html'


class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/all_blogs.html'


def single_blog(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    liked = False
    if request.user.is_authenticated:
        already_liked = Like.objects.filter(blog=blog, user=request.user)
        if already_liked:
            liked = True
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug': slug}))
    context = {'blog': blog, 'comment_form': comment_form, 'liked': liked}
    return render(request, 'app_blog/single_blog.html', context)


@login_required
def like_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked = Like(blog=blog, user=user)
        liked.save()
    return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug': blog.slug}))


@login_required
def dislike_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug': blog.slug}))


class DeleteBlogView(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'app_blog/my_blogs.html'
    success_url = reverse_lazy('app_blog:manage')

    def get_queryset(self):
        return Blog.objects.filter(user=self.request.user)

templates/app_blog/all_blogs.html
{% extends 'base.html' %}
{% block title_block %}Все посты - Эко-сообщество{% endblock  %}
{% load custom_filters %}
{% load static %}
{% block body_block %}
<main class="blog-grid-page">
    <div class="container">
        <p class='lead'>Все посты, написанные пользователями</p>
        <div class="row mt-2">
            {% for blog in blogs %}
            <div class="col-md-4 mb-4">
                <div class="card" style="height:400px">
                    <div class="overflow-hidden" style="height:200px">
                        <a href="{% url 'app_blog:blog' slug=blog.slug %}" class="text-dark text-decoration-none">
                        <img class="img-fluid w-100"
                            {% if blog.blog_image == "" %}
                                src="{% static '/images/empty.jpg' %}"
                            {% else %}
                                src="/media/{{blog.image}}"
                            {% endif %}
                        alt="">
                    </div>
                    <div class="px-3 py-1">
                        <p class="d-flex justify-content-between mb-1 text-secondary">
                            <span><i class="bi bi-calendar3 me-2"></i>{{blog.published|date}}</span>
                            <span><i class="bi bi-person-circle me-2"></i>{{blog.user}}</span>
                        </p>
                        <h5>{{blog.title|value_range:60}}</h5>
                        <p class="mb-0">{{blog.text|value_range:85}}</p>
                    </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock  %}

templates/app_blog/confirm.html
{% extends 'base.html' %}
{% block title_block %}Мои посты{% endblock %}
{% load static %}
{% block body_block %}
<div class="container">
{% if user.is_authenticated %}
    {% if msg %}
    <div class="alert alert-warning">{{msg}}</div>
    {% endif %}
{% else %}
    <p>Извините, но у вас нет прав к этому элементу</p>
{% endif %}
</div>
{% endblock %}

templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Написать пост - Эко-сообщество{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        <h2>Написать пост</h2>
        <p class="text-secondary">Добавьте информацию и сохраните пост, чтобы его опубликовать.</p>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-3" value="Сохранить">
        </form>
    </div>
</div>
{% endblock  %}

templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Редактировать пост - Эко-сообщества{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        <h2 class="mb-3">Редактировать</h2>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success mt-4" value="Обновить">
        </form>
    </div>
</div>
{% endblock  %}

templates/app_blog/my_blogs.html
{% extends 'base.html' %}
{% block title_block %}Мои посты - Эко-сообщество{% endblock %}
{% load custom_filters %}
{% load static %}
{% block body_block %}
<main class="blog-grid-page">
    <div class="container">
        <p class='lead'>Мои посты</p>
        <div class="row mt-2">
            {% for blog in user.blog_author.all %}
            <div class="col-md-4 mb-4">
                <div class="card" style="height:400px">
                    <div class="overflow-hidden">
                        <a href="{% url 'app_blog:blog' slug=blog.slug %}">
                            {% if blog.image %}
                            <img class="img-fluid w-100" src="/media/{{blog.image}}" alt=""></a>
                            {% else %}
                            <img class="img-fluid w-100" src="{% static '/images/empty.jpg' %}" alt=""></a>
                            {% endif %}
                    </div>
                    <div class="px-3 py-3">
                        <p class="d-flex justify-content-between mb-1 text-secondary">
                            <span><i class="bi bi-calendar3"></i> {{blog.published|date}}</span>
                            <span><i class="bi bi-person-circle"></i> {{blog.user}}</span>
                        </p>
                        <h5>{{blog.title|value_range:60}}</h5>
                        <p class="mb-0">{{blog.text|value_range:85}}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between py-4">
                        <a href="{% url 'app_blog:update' pk=blog.pk %}" class="btn btn-warning">Редактировать</a>
                        <form action="{% url 'app_blog:delete' pk=blog.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>У вас пока нет написанных постов</p>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock  %}

templates/app_blog/single_blog.html
{% extends 'base.html' %}
{% block title_block %}{{blog.title}} - Эко-сообщество{% endblock  %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_block %}
<main class="blog-post-single">
    <div class="container">
        <div class="row mt-2">
            <div class="col-md-8">
                <div class="mb-1 overflow-hidden rounded border">
                    <img class="img-fluid align-middle w-100"
                            {% if blog.blog_image == "" %}
                                src="{% static '/images/empty.jpg' %}"
                            {% else %}
                                src="/media/{{blog.image}}"
                            {% endif %}
                        alt="">
                </div>
                <p class="mx-2 text-secondary">
                <i class="bi bi-pencil-square"></i>
                Автор: <b>@/{{blog.user}}</b>
                <span class="mx-2"></span>Последнее обновление {{blog.edited}}
                </p>
                <div class="post-content">
                    <h4 class="fw-bold">{{blog.title}}</h4>
                    <p class="lead">{{blog.sub_title}}</p>
                    <p style="text-align:justify">{{blog.text|linebreaks}}</p>
                </div>

                {% if user.is_authenticated %}
                <form method="post" class="d-flex my-3">
                    {{comment_form|crispy}}
                    {% csrf_token %}
                    <button class="btn btn-dark me-2" type="submit"><i class="bi bi-chat-dots"></i> Комментировать</button>
                    {% if liked %}
                    <a class="btn btn-outline-danger" href="{% url 'app_blog:dislike' pk=blog.pk %}">
                    <i class="bi bi-hand-thumbs-down"></i></a>
                    {% else %}
                    <a class="btn btn-outline-success" href="{% url 'app_blog:like' pk=blog.pk %}">
                    <i class="bi bi-hand-thumbs-up"></i></a>
                    {% endif %}
                </form>
                {% else %}
                    <p class="lead">
                        <a class="text-decoration-none" href="{% url 'app_login:login' %}">
                        <i class="bi bi-person-circle"></i>
                        Войдите</a>, чтобы написать комментарий.
                    </p>
                {% endif %}

                <div class="card mb-5">
                    <div class="card-header">
                        <span>
                            <i class="bi bi-hand-thumbs-up"></i>
                            Нравится - <b>{{blog.blog_like.count}}</b>
                        </span>
                        <span class="ms-2">
                            <i class="bi bi-chat-right-quote ml-2"></i>
                            Комментариев - <b>{{blog.blog_comment.count}}</b>
                        </span>
                    </div>
                    <div class="card-body">
                        {% for comment in blog.blog_comment.all %}
                            <div class="card p-2 mb-1">
                                <div class="d-flex justify-content-between">
                                    <h5 class="m-0">
                                        {% if comment.user.first_name == "" %}
                                            {{comment.user}}
                                        {% else %}
                                        {{comment.user.first_name}} {{comment.user.last_name}}
                                        {% endif %}
                                    </h5>
                                    <p>{{comment.commented}}</p>
                                </div>
                                <p class="my-0">{{comment.comment}}</p>
                            </div>
                        {% empty %}
                        Пока к посту нет комментариев
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ms-5">
                    <h5 class="">Темы поста</h5>
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            {% for topic in blog.topics.all %}
                            <li class="list-group-item">{{ topic.title }}</li>
                            {% empty %}
                            <li class="list-group-item">Темы не выбраны</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock  %}